USER-SUPPLIED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ""
healthcheck:
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 6
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 6
    timeoutSeconds: 5
image:
  pullPolicy: IfNotPresent
  repository: aqaurius6666/cookie-fe
  tag: 7dc0c933
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
nameOverride: ""
nginx:
  enabled: true
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources:
  limits:
    cpu: 700m
    memory: 400Mi
  requests:
    cpu: 500m
    memory: 128Mi
securityContext: {}
service:
  port: 3000
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
sish-client:
  dns_resolver:
    enabled: false
  enabled: true
  service:
    name: nginx-ssh-tunnel
  services:
    sish:
      domain: 10.10.10.11
      from:
        domain: cookie-fe-nginx
        port: 8080
      port: 22222
      request:
        domain: cookie
        port: 80
tolerations: []
