
nginx:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  service:
    type: ClusterIP
    ports:
      http: 8080
  serverBlock: |
    proxy_cache_path /app levels=1:2 keys_zone=STATIC:30m use_temp_path=off inactive=7d max_size=2G loader_files=100 loader_sleep=50 loader_threshold=200;
    proxy_cache_valid 604800s; # 7 days
    proxy_cache_lock on;
    proxy_cache_use_stale updating;
    proxy_buffer_size 16k;
    proxy_buffers 16 16k;
    proxy_buffering on;
    proxy_http_version 1.1;
    proxy_ignore_headers Vary;
    proxy_ignore_headers Expires;
    proxy_ignore_headers Set-Cookie;
    proxy_ignore_headers Cache-Control;

    server {
      listen 8080;
      resolver kube-dns.kube-system valid=10s;
      server_name cookie.aqaurius6666.space;
      

      location ~ ^\/api\/(.*)$  {
          proxy_set_header Host $http_host;
          proxy_pass         http://cookie-be:3000;
          proxy_redirect     off;
          proxy_set_header   Host $host;
        }
      location /_next/static {
        proxy_cache STATIC;
        proxy_pass http://cookie-fe:3000;
        add_header X-Cache-Status $upstream_cache_status;
      }

      location /_next/image {
            proxy_pass http://cookie-fe:3000;

            # request_uri is important because images have GET params which define quality, url and size
            # $http_accept is important because it changes the response type of next/image
            proxy_cache_key "$request_uri$http_accept";

            proxy_cache STATIC;
      }
      location ~ ^/(?!api) {
        proxy_set_header Host $http_host;

        proxy_pass http://cookie-fe:3000;
      }
    }